//! CSV schema and row formatting for the example's three output streams.
//!
//! Each stream's column names live here once, next to the row builder that must
//! match them, so the header and the values cannot drift apart. The integration
//! tests assert that every header is a single physical line, that its names are
//! unique, and that a header's column count equals its row's field count.

use super::state::{FirmProbe, MacroEnvironment};

/// Columns of the per-tick headline stream printed to stdout.
pub const HEADLINE_COLUMNS: &[&str] = &[
    "tick",
    "production",
    "ppi",
    "cpi",
    "hpi",
    "rpi",
    "total_loans",
    "gdp_gap",
    "blocked_mortgages",
    "excess_demand",
    "prod_over_labour",
    "labour_over_materials",
    "employed",
    "individuals",
    "goods_demand",
    "goods_supply",
    "roa_apps",
    "roa_fails",
    "roa_max",
    "credit_req",
    "credit_granted",
    "sales_rev",
    "inv_chg",
    "costs",
    "c_wage",
    "c_interm",
    "c_cap",
    "c_tax",
    "c_int",
];

/// Columns of the aggregate trace written to `trace_aggregates.csv`.
pub const AGGREGATE_COLUMNS: &[&str] = &[
    "tick",
    "production",
    "ppi",
    "cpi",
    "hpi",
    "rpi",
    "employed",
    "individuals",
    "goods_demand",
    "goods_supply",
    "excess_demand",
    "sales_rev",
    "inv_chg",
    "costs",
    "c_wage",
    "c_interm",
    "c_cap",
    "c_tax",
    "c_int",
    "firm_deposits",
    "firm_debt",
    "firm_equity",
    "firms_bankrupt",
    "hh_deposits",
    "hh_ofa",
    "hh_income",
    "hh_consumption",
    "hh_net_wealth",
    "hh_bankrupt",
    "bank_equity",
    "bank_reserves",
    "bank_deposits",
    "gov_revenue",
    "gov_deficit",
    "gov_debt",
    "unemp_benefit",
    "avg_wage",
    "total_loans",
    "credit_req",
    "credit_granted",
    "roa_apps",
    "roa_fails",
    "roa_max",
    "bail_ins",
    "gdp_out",
    "gdp_exp",
    "b_loanint",
    "b_resinc",
    "b_rescost",
    "b_depint",
    "b_tax",
    "b_seized",
    "b_lost",
    "policy_rate",
    "cpi_infl",
    "growth",
    "blk_roa",
    "blk_cap",
    "blk_supply",
    "envelope",
    "cap_total",
    "cap_dte",
    "cap_roe",
    "dte_zero",
    "roe_zero",
    "d_interm",
    "d_fcap",
    "d_cons",
    "d_hcap",
    "d_gov",
    "d_exp",
];

/// Columns of the per-firm trace written to `trace_firms.csv`.
pub const FIRM_COLUMNS: &[&str] = &[
    "tick",
    "firm",
    "employees",
    "work_effort",
    "h_f0",
    "H",
    "M",
    "K",
    "target",
    "production",
    "price",
    "unit_cost",
    "demand",
    "excess_demand",
    "wage",
    "deposits",
    "debt",
    "equity",
    "profits",
    "sales",
    "inventory",
    "target_short_loan",
    "granted_short_loan",
];

/// Joins column names into a single CSV header line.
pub fn csv_header(columns: &[&str]) -> String {
    columns.join(",")
}

/// One headline row for the given model state, matching [`HEADLINE_COLUMNS`].
pub fn headline_row(state: &MacroEnvironment) -> String {
    let a = &state.audit;
    format!(
        "{},{:.6},{:.6},{:.6},{:.6},{:.6},{:.6},{:.6},{},{},{:.6},{:.6},{},{},{:.6},{:.6},{},{},{:.5},{:.2},{:.2},{:.1},{:.1},{:.1},{:.1},{:.1},{:.1},{:.1},{:.1}",
        state.quarter,
        state.aggregates.production,
        state.aggregates.ppi,
        state.aggregates.cpi,
        state.aggregates.hpi,
        state.aggregates.rpi,
        state.aggregates.total_loans,
        state.accounting.gdp.max_gap(),
        a.mortgage_blocked_purchases,
        a.goods_excess_demand,
        a.max_production_over_labour,
        a.max_labour_over_materials,
        a.employed_headcount,
        a.individual_headcount,
        a.goods_demand_quantity,
        a.goods_supply_quantity,
        a.firm_credit_applications,
        a.firm_credit_roa_failures,
        a.firm_roa_max,
        a.firm_credit_requested,
        a.firm_credit_granted,
        a.profit_sales_revenue,
        a.profit_inventory_change,
        a.profit_costs,
        a.cost_wages,
        a.cost_intermediate,
        a.cost_capital,
        a.cost_production_tax,
        a.cost_interest,
    )
}

/// One aggregate-trace row for the given model state, matching
/// [`AGGREGATE_COLUMNS`].
pub fn aggregate_row(state: &MacroEnvironment) -> String {
    let a = &state.audit;
    format!(
        "{},{:.4},{:.6},{:.6},{:.6},{:.6},{},{},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{},{:.4},{:.4},{:.4},{:.4},{:.4},{},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.6},{:.4},{:.4},{:.4},{:.4},{},{},{:.5},{},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.6},{:.6},{:.6},{},{},{},{:.3},{:.3},{:.3},{:.3},{},{},{:.2},{:.2},{:.2},{:.2},{:.2},{:.2}",
        state.quarter,
        state.aggregates.production,
        state.aggregates.ppi,
        state.aggregates.cpi,
        state.aggregates.hpi,
        state.aggregates.rpi,
        a.employed_headcount,
        a.individual_headcount,
        a.goods_demand_quantity,
        a.goods_supply_quantity,
        a.goods_excess_demand,
        a.profit_sales_revenue,
        a.profit_inventory_change,
        a.profit_costs,
        a.cost_wages,
        a.cost_intermediate,
        a.cost_capital,
        a.cost_production_tax,
        a.cost_interest,
        a.firm_deposits_total,
        a.firm_debt_total,
        a.firm_equity_total,
        a.firms_bankrupt,
        a.household_deposits_total,
        a.household_ofa_total,
        a.household_income_total,
        a.household_consumption_total,
        a.household_net_wealth_total,
        a.households_bankrupt,
        a.bank_equity_total,
        a.bank_reserves_total,
        a.bank_deposits_total,
        a.government_revenue,
        a.government_deficit,
        a.government_debt,
        a.unemployment_benefit,
        a.average_wage,
        state.aggregates.total_loans,
        a.firm_credit_requested,
        a.firm_credit_granted,
        a.firm_credit_applications,
        a.firm_credit_roa_failures,
        a.firm_roa_max,
        a.bank_bail_ins,
        state.aggregates.gdp.output,
        state.aggregates.gdp.expenditure,
        a.bank_loan_interest,
        a.bank_reserve_income,
        a.bank_reserve_cost,
        a.bank_deposit_interest,
        a.bank_corporate_tax,
        a.bank_writeoff_seized,
        a.bank_writeoff_lost,
        a.policy_rate,
        a.taylor_cpi_inflation,
        a.taylor_growth,
        a.credit_blocked_by_roa,
        a.credit_blocked_by_cap,
        a.credit_blocked_by_supply,
        a.credit_envelope_total,
        a.credit_cap_total,
        a.cap_dte_total,
        a.cap_roe_total,
        a.cap_dte_zero,
        a.cap_roe_zero,
        a.demand_firm_intermediate,
        a.demand_firm_capital,
        a.demand_household_consumption,
        a.demand_household_capital,
        a.demand_government,
        a.demand_export,
    )
}

/// One per-firm trace row for `firm` at `quarter`, matching [`FIRM_COLUMNS`].
pub fn firm_row(quarter: u64, firm: &FirmProbe) -> String {
    format!(
        "{},{},{},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4},{:.4}",
        quarter,
        firm.id,
        firm.employees,
        firm.work_effort,
        firm.initial_work_effort,
        firm.labour,
        firm.intermediate_constraint,
        firm.capital_constraint,
        firm.target_production,
        firm.production,
        firm.price,
        firm.unit_cost,
        firm.demand,
        firm.excess_demand,
        firm.wage,
        firm.deposits,
        firm.debt,
        firm.equity,
        firm.profits,
        firm.sales_quantity,
        firm.inventory,
        firm.target_short_loan,
        firm.granted_short_loan,
    )
}
